In [63]:
import pandas as pd
from sqlalchemy import create_engine

In [64]:
gdp_file = "GDP By Country.csv"
gdp_df = pd.read_csv(gdp_file)
gdp_df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,Aruba,ABW,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2.498883e+09,2.390503e+09,2.549721e+09,2.534637e+09,2.581564e+09,2.649721e+09,2.691620e+09,2.646927e+09,2.700559e+09,NaN
1,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,537777811.1,548888895.6,546666677.8,751111191.1,800000044.4,1.006667e+09,...,1.243909e+10,1.585657e+10,1.780429e+10,1.990732e+10,2.056107e+10,2.048489e+10,1.990711e+10,1.904636e+10,1.954398e+10,NaN
2,Angola,AGO,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,7.030716e+10,8.379950e+10,1.117900e+11,1.280530e+11,1.367100e+11,1.457120e+11,1.161940e+11,1.011240e+11,1.221240e+11,NaN
3,Albania,ALB,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.204421e+10,1.192696e+10,1.289087e+10,1.231978e+10,1.277628e+10,1.322825e+10,1.138693e+10,1.188368e+10,1.303854e+10,NaN
4,Andorra,AND,GDP (current US$),NY.GDP.MKTP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,3.660531e+09,3.355695e+09,3.442063e+09,3.164615e+09,3.281585e+09,3.350736e+09,2.811489e+09,2.877312e+09,3.012914e+09,NaN

In [65]:
gdp_new = gdp_df.drop(columns=['Country Code','Indicator Name','Indicator Code'])
gdp_new.drop('2018',axis=1, inplace=True)

In [66]:
rename = gdp_new.rename(columns={'Country Name':'Country'})
rename2 = rename.set_index('Country')
rename3 = rename2.add_suffix(' gdp')

In [67]:
clean_gdp = rename3.dropna()
final_gdp = clean_gdp.drop(clean_gdp.columns.to_series()["1960":"1989"],axis=1)

In [68]:
final_gdp.to_csv('clean_gdp_file.csv')

In [69]:
clean_gdp_file = pd.read_csv('clean_gdp_file.csv')
clean_gdp_file

,Country,1989 gdp,1990 gdp,1991 gdp,1992 gdp,1993 gdp,1994 gdp,1995 gdp,1996 gdp,1997 gdp,...,2008 gdp,2009 gdp,2010 gdp,2011 gdp,2012 gdp,2013 gdp,2014 gdp,2015 gdp,2016 gdp,2017 gdp
0,Australia,2.993180e+11,3.108380e+11,3.253580e+11,3.248780e+11,3.115290e+11,3.222010e+11,3.672160e+11,4.003030e+11,4.345680e+11,...,1.052580e+12,9.264480e+11,1.144260e+12,1.394280e+12,1.543410e+12,1.573700e+12,1.464960e+12,1.349030e+12,1.208040e+12,1.323420e+12
1,Austria,1.331060e+11,1.664630e+11,1.737940e+11,1.950780e+11,1.903800e+11,2.035350e+11,2.410380e+11,2.372510e+11,2.127900e+11,...,4.302940e+11,4.001720e+11,3.918930e+11,4.311200e+11,4.094250e+11,4.300690e+11,4.418850e+11,3.820660e+11,3.908000e+11,4.165960e+11
2,Burundi,1.113924e+09,1.132101e+09,1.167398e+09,1.083038e+09,9.386326e+08,9.250306e+08,1.000428e+09,8.690339e+08,9.728963e+08,...,1.611836e+09,1.781455e+09,2.032135e+09,2.235821e+09,2.333308e+09,2.451625e+09,2.705783e+09,3.104395e+09,2.959185e+09,3.172416e+09
3,Belgium,1.651000e+11,2.064310e+11,2.116380e+11,2.360380e+11,2.259250e+11,2.461950e+11,2.895670e+11,2.813580e+11,2.548140e+11,...,5.186260e+11,4.845530e+11,4.835480e+11,5.270080e+11,4.978840e+11,5.209250e+11,5.307710e+11,4.550400e+11,4.675460e+11,4.926810e+11
4,Benin,1.502294e+09,1.959965e+09,1.986438e+09,1.695315e+09,2.274558e+09,1.598076e+09,2.169627e+09,2.361117e+09,2.268302e+09,...,7.132787e+09,7.097199e+09,6.970241e+09,7.814081e+09,8.152554e+09,9.157356e+09,9.707432e+09,8.291156e+09,8.573160e+09,9.246697e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,St. Vincent and the Grenadines,2.147450e+08,2.403653e+08,2.548296e+08,2.779541e+08,2.863078e+08,2.894385e+08,3.160085e+08,3.314897e+08,3.477700e+08,...,6.954289e+08,6.749225e+08,6.812260e+08,6.761294e+08,6.929337e+08,7.212090e+08,7.277144e+08,7.554580e+08,7.707622e+08,7.852225e+08
120,World,2.010400e+13,2.260710e+13,2.395130e+13,2.543880e+13,2.585290e+13,2.776750e+13,3.087050e+13,3.156190e+13,3.145380e+13,...,6.357490e+13,6.026710e+13,6.596590e+13,7.331680e+13,7.499370e+13,7.709880e+13,7.918850e+13,7.491610e+13,7.599740e+13,8.073760e+13
121,South Africa,1.289030e+11,1.155530e+11,1.239430e+11,1.345450e+11,1.343100e+11,1.397520e+11,1.554600e+11,1.476080e+11,1.525860e+11,...,2.867700e+11,2.959360e+11,3.753490e+11,4.164190e+11,3.963280e+11,3.666430e+11,3.506360e+11,3.175370e+11,2.957470e+11,3.488720e+11
122,Zambia,3.998638e+09,3.285217e+09,3.378882e+09,3.181922e+09,3.273238e+09,3.656648e+09,3.807067e+09,3.597221e+09,4.303282e+09,...,1.791086e+10,1.532834e+10,2.026556e+10,2.346010e+10,2.550337e+10,2.804546e+10,2.715063e+10,2.115439e+10,2.095475e+10,2.586814e+10
123,Zimbabwe,8.286323e+09,8.783817e+09,8.641482e+09,6.751472e+09,6.563813e+09,6.890675e+09,7.111271e+09,8.553147e+09,8.529572e+09,...,4.415703e+09,9.665793e+09,1.204166e+10,1.410192e+10,1.711485e+10,1.909102e+10,1.949552e+10,1.996312e+10,2.054868e+10,2.204090e+10